addons: 
    apt:
        sources:   
            - ubuntu-toolchain-r-test 
        packages:   
            - gcc-4.8 
            - g++-4.8
language: cpp
install: true
script:
- ./waf clean
- ./waf configure --build-profile=optimized --enable-examples
- ./waf
